cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null


class Cat < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :color, presence: true
  validates :sex, presence: true
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end
  
  def new
    @cat = Cat.new

  end
  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cats_url

    end

  end

  def update
    @cat = Cat.find(params[:id])
    if cat.update(cat_params)
      redirect_to cats_url(cat)
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end
  
  private
  def cat_params
    params.require(:cat).permit(:name,:birth_date,:color,:description,:sex)
  end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cats_helper.rb
module CatsHelper
end

cats99/app/views/cats/_cats.html.erb
<% if action == :index%>
  <li>
      <ul>
      <li>id: <%=cat.id%></li>
      <li>name: <%=cat.name%></li>
      <li>birthdate: <%=cat.birth_date%></li>
      <li>color: <%=cat.color%></li>
      <li>sex: <%=cat.sex%></li>
      <li>description: <%=cat.description%></li>
      </ul>
      <br>
  </li>
<% elsif action == :show%>
  <li>
      <ul>
      <li>name: <%=cat.name%></li>
      <li>birthdate: <%=cat.birth_date%></li>
      <li>color: <%=cat.color%></li>
      <li>sex: <%=cat.sex%></li>
      <li>description: <%=cat.description%></li>
      </ul>
      <br>
  </li>
  <%end%>

cats99/app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
<% elsif type == :edit %>
<% action_url = cat_url(cat) %>

<% end %>

<form action= "<%= action_url %>" method= "post"> 
<%if type == :edit %>
<input type="hidden" name="_method" value="patch"></input>
<% end %>
  <label for="name">Name: </label>

  <input type= "text" id= "name" name= "cat[name]" value="<%=cat.name%>"></input>
  <br>
  <br>
  <label for="birth_date">Birthdate: </label>
  <input type= "text" id="birth_date" name="cat[birth_date]" value="<%=cat.birth_date%>"></input>
  <p>Select a sex: &nbsp &nbsp
  <label for="sex">M &nbsp</label>
  <input type= "radio" id="m" name="cat[sex]" value="M"></input>
  <label for="sex">F</label>
  <input type= "radio" id="f" name="cat[sex]" value="F"></input>
  </p>
  <label for="color">Color: </label>
  <select id= "color", name= "cat[color]" value = "<%cat.color%>"></input>
    <option value="">--Please choose an option--</option>
    <option value="red">red</option>
    <option value="white">white</option>
    <option value="blue">blue</option>
    <option value="audi">audi</option>
  </select>
  <br>
  <br>
  <label for="description">Description: </label>

  <input type= "text" id="description" name="cat[description]" value="<%=cat.description%>"></input>
  <br>
  <br>
  <input type="submit" value= "GIVE ME YOUR EL GATO"></input>
  
</form>

cats99/app/views/cats/edit.html.erb
<h2>Edit cat</h2>
<%= render 'form', cat: @cat, type: :edit %>

cats99/app/views/cats/index.html.erb
<h2>All Cats</h2>

<ul> 
  <% @cats.each do |cat| %>
    <%= render 'cats', cat: cat, action: :index %>
  <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<h2>Add New Cat</h2>
<%= render 'form', cat: @cat, type: :new %>

cats99/app/views/cats/show.html.erb
<%= render 'cats', cat: @cat, action: :show %>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>